- hosts: all
  user: '{{ ansible_ssh_user }}'
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name:
      shell: 'docker run -itd --name sphinx-plugin-btc --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro entropypool/btc-chain-sphinx:22.0'
      #      register: process
      #      ignore_errors: true
      #    - name: Print processes
      #      debug: var=process.stdout_lines
