- hosts: all
  user: '{{ ansible_ssh_user }}'
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: pull image
      shell: 'docker pull uhub.service.ucloud.cn/entropypool/btc-chain-sphinx:{{ version }}'
    - name: docker stop sphinx plugin btc
      shell: 'docker stop sphinx-plugin-btc; docker rm sphinx-plugin-btc'
    - name: docker run sphinx plugin btc
      shell: 'docker run -itd --name sphinx-plugin-btc --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro entropypool/btc-chain-sphinx:{{ version }}'
    - name: install sphinx plugin btc
      shell: 'docker exec -it sphinx-plugin-btc /home/install-btc.sh -u {{ rpcuser }} -p {{ rpcpassword }} -v {{ version }} -P {{ phinxproxyapi }}'
